name: Daily Task - Run Python Script

on:
  schedule:
    - cron: '0 1 * * *'  # Her gün saat 01:00'de çalışacak
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Python kurulumu
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 2. Gereksinimleri yükle
      - name: Install dependencies
        run: |
          pip install requests pandas openpyxl

      # 3. Repo'yu tam geçmişle çek
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Tüm commit geçmişini al

      # 4. Script'i çalıştır
      - name: Run Python script
        run: python code.py

      # 5. Değişiklikleri STASH'le (geçici sakla)
      - name: Stash local changes
        run: git stash push -u

      # 6. Uzak değişiklikleri çek
      - name: Pull latest changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull origin main --rebase

      # 7. STASH'lenmiş değişiklikleri geri yükle
      - name: Pop stashed changes
        run: git stash pop

      # 8. Değişiklikleri commit et ve pushla
      - name: Commit and push
        run: |
          git add Data.xlsx
          git commit -m "Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
