name: Daily Task - Run Python Script

on:
  schedule:
    - cron: '0 1 * * *'  # Her gün saat 01:00'de çalışacak
  workflow_dispatch:  # Manuel olarak tetiklenebilir

permissions:
  contents: write  # Repo içeriğine yazma izni veriyoruz

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Ubuntu ortamında çalışacak

    steps:
      # 1. Python ortamını kur
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Python 3.9 versiyonu kullanılacak

      # 2. Gereksinimleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      # 3. Repo'yu çek
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Tüm commit geçmişini çeker

      # 4. Python script'ini çalıştır
      - name: Run Python script
        run: |
          python code.py  # Python script'inizi çalıştırır

      # 5. Değişiklikleri çek ve merge et
      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase  # Uzaktaki değişiklikleri rebase ile birleştir

      # 6. Değişiklikleri commit et ve pushla
      - name: Commit and push changes
        run: |
          git add Data.xlsx  # Doğru dosya adını kullanın
          git commit -m "Update Data2.xlsx with new fuel prices"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
