name: Daily Task - Run Python Script

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: 

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Python ortamını kur
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 2. Gereksinimleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      # 3. Repo'yu çek
      - name: Checkout repository
        uses: actions/checkout@v2

      # 4. Python script'i çalıştır
      - name: Run Python script
        run: |
          python code.py

      # 5. Değişiklikleri commit et ve pushla
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data.xlsx
          git commit -m "Update data.xlsx with new fuel prices"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
